apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roadwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - name: frontend
        image: registry.gitlab.com/fatikasraoui2003/nid-de-poule-website/frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roadwatch
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
